
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization: always
    url: ${databaseUrl}
    username: ${usernameDB}
    password: ${passwordDB}
    platform: org.hibernate.dialect.MySQL8Dialect
    hikari:
      connection-test-query: SELECT 1

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    schemas: heroku_13a6e82d03944bb

server:
  cors:
    allowed-origins: "*"